name: Daily QT Bot

on:
  schedule:
    - cron: '5 22 * * *'
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Seoul
    permissions: # 중요: 저장소 쓰기 권한 추가
      contents: write
      
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: pip install requests beautifulsoup4
        
      - name: Run Bot and Create File
        env:
          KAKAO_CLIENT_ID: ${{ secrets.KAKAO_CLIENT_ID }}
          KAKAO_REFRESH_TOKEN: ${{ secrets.KAKAO_REFRESH_TOKEN }}
        run: python QT_BOT.py
        
      # 생성된 파일을 저장소에 업데이트하는 단계
      - name: Commit and Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "action@github.com"
          git add data/*.html  # 이 부분이 .md에서 .html로 바뀌었는지 확인!
          git commit -m "Update Today's QT (HTML)" || echo "No changes to commit"
          git push
