name: Daily QT Bot

on:
  schedule:
    - cron: '5 21 * * *'
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Seoul
    permissions: # 중요: 저장소 쓰기 권한 추가
      contents: write
      
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: pip install requests beautifulsoup4
        
      - name: Run Bot and Create File
        env:
          KAKAO_CLIENT_ID: ${{ secrets.KAKAO_CLIENT_ID }}
          KAKAO_REFRESH_TOKEN: ${{ secrets.KAKAO_REFRESH_TOKEN }}
        run: python QT_BOT.py
        
      # 생성된 파일을 저장소에 업데이트하는 단계
      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          # 뒤에 || echo "No changes" 를 붙여주면 바뀐 게 없어도 에러 없이 통과합니다.
          git commit -m "정기 QT 업데이트 (${{ env.DATE }})" || echo "No changes to commit"
          git push origin main || echo "Nothing to push"
